-- Reset admin password to 'admin123'
-- bcrypt hash generated by bcryptjs
UPDATE users SET password_hash = '$2a$10$EdEwOlFEWK1e/xKlrTO2fOBGHc2.fCnjDIPQMjLB/FVS4qQnmVawy' WHERE email = 'admin@acl.sn';
